"""create_pr node: commit, push, create PR/MR, notify (PRD sections 54-56)."""

from __future__ import annotations

from pathlib import Path

from nightshift.app.config.logging import get_logger
from nightshift.app.persistence.models import PullRequest
from nightshift.app.sandbox.command_runner import CommandRunner
from nightshift.app.workflow.context import WorkflowContext
from nightshift.app.workflow.state import State
from nightshift.integrations.git_provider.base import PullRequestRequest
from nightshift.integrations.git_provider.registry import get_git_provider
from nightshift.integrations.task_provider.ace_mcp import update_ace_status
from nightshift.integrations.telegram.bot import TelegramClient
from nightshift.integrations.telegram.formatter import format_completed

logger = get_logger(__name__)


def _commit_message(task: dict) -> str:
    title = task.get("title", "update").strip().lower()
    scope = ""
    if ":" in title:
        scope, title = title.split(":", 1)
        scope = scope.strip()
    return f"feat({scope}): {title}" if scope else f"feat: {title}"


async def create_pr(ctx: WorkflowContext) -> State:
    workspace_path = ctx.get("workspace_path")
    branch_name = ctx.get("branch_name")
    task = ctx.get("task", {})
    repository = ctx.get("repository", {})

    if not workspace_path or not branch_name:
        ctx.set("error", {"type": "GIT_FAILURE", "message": "Missing workspace/branch"})
        return State.FAILED

    runner = CommandRunner(allowed_cwd=Path(workspace_path))
    workspace = Path(workspace_path)

    # Commit
    await runner.execute(["git", "add", "-A"], cwd=workspace)
    commit_result = await runner.execute(
        ["git", "commit", "-m", _commit_message(task)],
        cwd=workspace,
        timeout=120,
    )
    if not commit_result.success and "nothing to commit" not in commit_result.stdout:
        logger.error("commit_failed", stderr=commit_result.stderr)

    # Push
    push_result = await runner.execute(
        ["git", "push", "-u", "origin", branch_name],
        cwd=workspace,
        timeout=300,
    )
    if not push_result.success:
        ctx.set("error", {"type": "GIT_FAILURE", "message": push_result.stderr})
        return State.FAILED

    # Create PR/MR
    provider_name = repository.get("provider", "gitlab")
    default_branch = repository.get("default_branch", "main")

    title = f"feat: {task.get('title', ctx.execution.external_task_id)}"
    body = _pr_body(ctx, branch_name)

    provider = get_git_provider(ctx.settings, provider_name)
    pr_result = await provider.create_pull_request(
        PullRequestRequest(
            repository=repository.get("name", ""),
            title=title,
            body=body,
            head_branch=branch_name,
            base_branch=default_branch,
        )
    )

    ctx.session.add(
        PullRequest(
            task_execution_id=ctx.execution_id,
            provider=provider_name,
            external_pr_id=pr_result.external_id,
            number=pr_result.number,
            title=title,
            url=pr_result.url,
            branch_name=branch_name,
        )
    )
    ctx.session.flush()
    ctx.set("pull_request", pr_result.model_dump())

    # Move Ace task to IN_REVIEW now that the PR is up.
    await update_ace_status(ctx.task_provider, ctx.execution.external_task_id, "IN_REVIEW")

    # Notify
    telegram = TelegramClient(ctx.settings.telegram_bot_token, ctx.settings.telegram_chat_id)
    if telegram.configured:
        text = format_completed(
            title=task.get("title", ""),
            pr_url=pr_result.url or str(pr_result.number),
            branch=branch_name,
            repair_attempts=ctx.execution.repair_attempt,
        )
        await telegram.send_message(text)

    return State.PR_CREATED

def _pr_body(ctx: WorkflowContext, branch_name: str) -> str:
    task = ctx.get("task", {})
    validation = ctx.get("validation_result", {})
    plan = ctx.get("implementation_plan", {})

    steps = plan.get("steps", [])
    steps_text = "\n".join(f"- {s.get('action')}" for s in steps) or "- (none)"

    stages = validation.get("stages", {})
    validation_text = "\n".join(
        f"{'✅' if v.get('status') == 'PASS' else '❌'} {k}" for k, v in stages.items()
    ) or "(not run)"

    acs = task.get("acceptance_criteria", [])
    ac_text = "\n".join(f"✅ {ac}" for ac in acs) or "(none provided)"

    return (
        f"Task\n{task.get('id')}\n\n"
        f"Summary\n{task.get('description', '')}\n\n"
        f"Implementation\n{steps_text}\n\n"
        f"Validation\n{validation_text}\n\n"
        f"Acceptance Criteria\n{ac_text}\n\n"
        f"Branch\n{branch_name}\n\n"
        f"Generated by\n🌙 Night Shift"
    )
